import { IWorldAreas } from '../models/world-areas.model';

export const europeAreas: IWorldAreas = {
  areaName: 'Europe',
  countriesCapitals: [
    'Amsterdam',
    'Athens',
    'Belgrade',
    'Bratislava',
    'Brussels',
    'Berlin',
    'Budapest',
    'Copenhagen',
    'Dublin',
    'Kiev',
    'Lisbon',
    'London',
    'Luxembourg',
    'Madrid',
    'Minsk',
    'Monaco',
    'Moscow',
    'Oslo',
    'Paris',
    'Prague',
    'Rome',
    'Sofia',
    'Stockholm',
    'Vienna',
    'Warsaw',
  ],
};
