import { IWorldAreas } from '../models/world-areas.model';

export const europeAreas: IWorldAreas = {
  areaName: 'Europe',
  countriesCapitals: [
    'Amsterdam',
    'Berlin',
    'Bern',
    'Brussels',
    'Bucharest',
    'Budapest',
    'Dublin',
    'Helsinki',
    'Kiev',
    'Lisbon',
    'London',
    'Madrid',
    'Minsk',
    'Moscow',
    'Oslo',
    'Paris',
    'Prague',
    'Reykjavik',
    'Rome',
    'Sofia',
    'Stockholm',
    'Tallinn',
    'Vatican City',
    'Vienna',
    'Warsaw',
  ],
};

export const americasAreas: IWorldAreas = {
  areaName: 'America',
  countriesCapitals: [
    'Buenos Aires',
    'Brasilia',
    'Ottawa',
    'Santiago de Chile',
    'Bogota',
    'San José',
    'Havana',
    'Roseau',
    'Tegucigalpa',
    'Mexico City',
    'Panama',
    'Asuncion',
    'Washington D. C.',
    'Montevideo',
    'Caracas',
  ],
};

export const asianAreas: IWorldAreas = {
  areaName: 'Asia',
  countriesCapitals: [
    'Kabul',
    'Baku',
    'Beijing',
    'Tbilisi',
    'New Delhi',
    'Jakarta',
    'Tehran',
    'Jerusalem',
    'Tokyo',
    'Astana',
    'Pionyang',
    'Doha',
    'Moscow',
    'Riad',
    'Singapore',
    'Seoul',
    'Damascus',
    'Dushanbe',
    'Bangkok',
    'Ankara',
    'Ashgabat',
    'Abu Dhabi',
    'Tashkent',
  ],
};

export const africanAreas: IWorldAreas = {
  areaName: 'Africa',
  countriesCapitals: [
    'Abuja',
    'Accra',
    'Bangui',
    'Brazzaville',
    'Cairo',
    'Dakar',
    'Juba',
    'Khartoum',
    'Luanda',
    'Moroni',
    'Nairobi',
    'Niamey',
    'Pretoria',
    'Rabat',
    'Tunis',
  ],
};
